version: '3'

services:
  database:
    image: postgres:latest
    ports: ["5432:5432"]

    environment:
        POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
        POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
        POSTGRES_DB: inventaurus # The PostgreSQL default database (automatically created at first launch)
    
  nextapp:
    build:
      context: ./inventaurus
    ports:
      - "3000:3000"

  
